"""The Juggler client: invisible_playwright's engine, copied and adapted.

| module | what it does |
|---|---|
| `connection.py` | the pipe to Juggler. JSON delimited by a zero byte; fd 3/4 on POSIX, inheritable HANDLEs on Windows |
| `protocol.py` | GENERATED by `scripts/gen_juggler_protocol.py` from the `Protocol.js` inside the shipped binary |
| `browser.py` | a launched browser, its contexts and its pages; extracted from invisible_playwright's `server.py` without the Playwright channel |
| `lifecycle.py` | frame tree, navigations, the four load states |
| `injected.py` | loads `injected.js` into the UTILITY world and calls it; here also the crossings `execute_script` needs |
| `injected.js` | the selector engines and actionability checks, with the fork's stealth fixes |
| `actions.py` | the retry loop and every input action; here the engine also draws every pointer APPROACH |
| `keyboard.py`, `keylayout.py` | from a key name to the four fields `Page.dispatchKeyEvent` demands |

⛔ COPIED FROM invisible_playwright ON 2026-09-24, and the two copies are
meant to stay the same engine. The differences are deliberate and short:
`browser.py` exists (there it is inside the Playwright server), `actions.py`
glides the pointer to every target (there a client-side wrapper does it), and
`injected.py` has the main-world helpers at its end. A fix to anything else in
this folder belongs in both repositories.
"""
